services:
  frontend:
    build: ./frontend
    container_name: TheFoodHub-frontend-container
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - app-network

  auth-service:
    build: ./AuthService
    container_name: auth-service-container
    ports:
      - '4001:4001'
    volumes:
      - ./AuthService:/app
      - /app/node_modules
    env_file:
      - ./AuthService/.env
    networks:
      - app-network

  delivery-service:
    build: ./DeliveryService
    container_name: delivery-service-container
    ports:
      - '4002:4002'
    volumes:
      - ./DeliveryService:/app
      - /app/node_modules
    env_file:
      - ./DeliveryService/.env
    networks:
      - app-network

  notification-service:
    build: ./NotificationService
    container_name: notification-service-container
    ports:
      - '4005:4005'
    volumes:
      - ./NotificationService:/app
      - /app/node_modules
    env_file:
      - ./NotificationService/.env
    networks:
      - app-network

  order-service:
    build: ./OrderService
    container_name: order-service-container
    ports:
      - '4003:4003'
    volumes:
      - ./OrderService:/app
      - /app/node_modules
    env_file:
      - ./OrderService/.env
    networks:
      - app-network

  payment-service:
    build: ./PaymentService
    container_name: payment-service-container
    ports:
      - '4000:4000'
    volumes:
      - ./PaymentService:/app
      - /app/node_modules
    env_file:
      - ./PaymentService/.env
    networks:
      - app-network

  restuarant-service:  
    build: ./RestuarantService   
    container_name: restuarant-service-container
    ports:
      - '4004:4004'
    volumes:
      - ./RestuarantService:/app
      - /app/node_modules
    env_file:
      - ./RestuarantService/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
