services:
  backend:
    build: ./backend
    container_name: TheFoodHub-backend-container
    ports:
      - '4000:4000'
    volumes:
      - ./backend:backend
      - ./backend/node_modules
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    container_name: TheFoodHub-frontend-container
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:frontend
      - ./frontend/node_modules
    stdin_open: true
    tty: true  
